//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksUnitTests.StackHashWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15", ConfigurationName="StackHashWebService.StackHashServiceSoap")]
    public interface StackHashServiceSoap {
        
        // CODEGEN: Generating message contract since element name error from namespace http://www.stackhash.com/services/2010/04/15 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stackhash.com/services/2010/04/15/ReportError", ReplyAction="*")]
        TasksUnitTests.StackHashWebService.ReportErrorResponse ReportError(TasksUnitTests.StackHashWebService.ReportErrorRequest request);
        
        // CODEGEN: Generating message contract since element name error from namespace http://www.stackhash.com/services/2010/04/15 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stackhash.com/services/2010/04/15/ReportErrorFromUser", ReplyAction="*")]
        TasksUnitTests.StackHashWebService.ReportErrorFromUserResponse ReportErrorFromUser(TasksUnitTests.StackHashWebService.ReportErrorFromUserRequest request);
        
        // CODEGEN: Generating message contract since element name CheckForUpdateResult from namespace http://www.stackhash.com/services/2010/04/15 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stackhash.com/services/2010/04/15/CheckForUpdate", ReplyAction="*")]
        TasksUnitTests.StackHashWebService.CheckForUpdateResponse CheckForUpdate(TasksUnitTests.StackHashWebService.CheckForUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stackhash.com/services/2010/04/15/ReportIndexStatistics", ReplyAction="*")]
        void ReportIndexStatistics(System.Guid serviceInstance, int contextId, int products, int files, int events, int eventInfos, int cabs, int maxEventCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stackhash.com/services/2010/04/15/ReportDotNetMiss", ReplyAction="*")]
        void ReportDotNetMiss(System.Guid serviceInstance, int contextId, int dotNetMajor, int dotNetMinor, int dotNetBuild, int dotNetPrivate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stackhash.com/services/2010/04/15/RemoveTestData", ReplyAction="*")]
        void RemoveTestData();
        
        // CODEGEN: Generating message contract since element name companyName from namespace http://www.stackhash.com/services/2010/04/15 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stackhash.com/services/2010/04/15/GetLicense", ReplyAction="*")]
        TasksUnitTests.StackHashWebService.GetLicenseResponse GetLicense(TasksUnitTests.StackHashWebService.GetLicenseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportError", Namespace="http://www.stackhash.com/services/2010/04/15", Order=0)]
        public TasksUnitTests.StackHashWebService.ReportErrorRequestBody Body;
        
        public ReportErrorRequest() {
        }
        
        public ReportErrorRequest(TasksUnitTests.StackHashWebService.ReportErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15")]
    public partial class ReportErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        public ReportErrorRequestBody() {
        }
        
        public ReportErrorRequestBody(string error) {
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportErrorResponse", Namespace="http://www.stackhash.com/services/2010/04/15", Order=0)]
        public TasksUnitTests.StackHashWebService.ReportErrorResponseBody Body;
        
        public ReportErrorResponse() {
        }
        
        public ReportErrorResponse(TasksUnitTests.StackHashWebService.ReportErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15")]
    public partial class ReportErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReportErrorResult;
        
        public ReportErrorResponseBody() {
        }
        
        public ReportErrorResponseBody(bool ReportErrorResult) {
            this.ReportErrorResult = ReportErrorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportErrorFromUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportErrorFromUser", Namespace="http://www.stackhash.com/services/2010/04/15", Order=0)]
        public TasksUnitTests.StackHashWebService.ReportErrorFromUserRequestBody Body;
        
        public ReportErrorFromUserRequest() {
        }
        
        public ReportErrorFromUserRequest(TasksUnitTests.StackHashWebService.ReportErrorFromUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15")]
    public partial class ReportErrorFromUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sender;
        
        public ReportErrorFromUserRequestBody() {
        }
        
        public ReportErrorFromUserRequestBody(string error, string sender) {
            this.error = error;
            this.sender = sender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportErrorFromUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportErrorFromUserResponse", Namespace="http://www.stackhash.com/services/2010/04/15", Order=0)]
        public TasksUnitTests.StackHashWebService.ReportErrorFromUserResponseBody Body;
        
        public ReportErrorFromUserResponse() {
        }
        
        public ReportErrorFromUserResponse(TasksUnitTests.StackHashWebService.ReportErrorFromUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15")]
    public partial class ReportErrorFromUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReportErrorFromUserResult;
        
        public ReportErrorFromUserResponseBody() {
        }
        
        public ReportErrorFromUserResponseBody(bool ReportErrorFromUserResult) {
            this.ReportErrorFromUserResult = ReportErrorFromUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForUpdate", Namespace="http://www.stackhash.com/services/2010/04/15", Order=0)]
        public TasksUnitTests.StackHashWebService.CheckForUpdateRequestBody Body;
        
        public CheckForUpdateRequest() {
        }
        
        public CheckForUpdateRequest(TasksUnitTests.StackHashWebService.CheckForUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15")]
    public partial class CheckForUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int clientMajor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int clientMinor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid clientInstance;
        
        public CheckForUpdateRequestBody() {
        }
        
        public CheckForUpdateRequestBody(int clientMajor, int clientMinor, System.Guid clientInstance) {
            this.clientMajor = clientMajor;
            this.clientMinor = clientMinor;
            this.clientInstance = clientInstance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForUpdateResponse", Namespace="http://www.stackhash.com/services/2010/04/15", Order=0)]
        public TasksUnitTests.StackHashWebService.CheckForUpdateResponseBody Body;
        
        public CheckForUpdateResponse() {
        }
        
        public CheckForUpdateResponse(TasksUnitTests.StackHashWebService.CheckForUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15")]
    public partial class CheckForUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckForUpdateResult;
        
        public CheckForUpdateResponseBody() {
        }
        
        public CheckForUpdateResponseBody(string CheckForUpdateResult) {
            this.CheckForUpdateResult = CheckForUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLicenseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLicense", Namespace="http://www.stackhash.com/services/2010/04/15", Order=0)]
        public TasksUnitTests.StackHashWebService.GetLicenseRequestBody Body;
        
        public GetLicenseRequest() {
        }
        
        public GetLicenseRequest(TasksUnitTests.StackHashWebService.GetLicenseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15")]
    public partial class GetLicenseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid licenseId;
        
        public GetLicenseRequestBody() {
        }
        
        public GetLicenseRequestBody(System.Guid licenseId) {
            this.licenseId = licenseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLicenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLicenseResponse", Namespace="http://www.stackhash.com/services/2010/04/15", Order=0)]
        public TasksUnitTests.StackHashWebService.GetLicenseResponseBody Body;
        
        public GetLicenseResponse() {
        }
        
        public GetLicenseResponse(TasksUnitTests.StackHashWebService.GetLicenseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stackhash.com/services/2010/04/15")]
    public partial class GetLicenseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetLicenseResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string departmentName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long maxEvents;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int maxSeats;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime expiryUTC;
        
        public GetLicenseResponseBody() {
        }
        
        public GetLicenseResponseBody(bool GetLicenseResult, string companyName, string departmentName, long maxEvents, int maxSeats, System.DateTime expiryUTC) {
            this.GetLicenseResult = GetLicenseResult;
            this.companyName = companyName;
            this.departmentName = departmentName;
            this.maxEvents = maxEvents;
            this.maxSeats = maxSeats;
            this.expiryUTC = expiryUTC;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StackHashServiceSoapChannel : TasksUnitTests.StackHashWebService.StackHashServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StackHashServiceSoapClient : System.ServiceModel.ClientBase<TasksUnitTests.StackHashWebService.StackHashServiceSoap>, TasksUnitTests.StackHashWebService.StackHashServiceSoap {
        
        public StackHashServiceSoapClient() {
        }
        
        public StackHashServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StackHashServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StackHashServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StackHashServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TasksUnitTests.StackHashWebService.ReportErrorResponse TasksUnitTests.StackHashWebService.StackHashServiceSoap.ReportError(TasksUnitTests.StackHashWebService.ReportErrorRequest request) {
            return base.Channel.ReportError(request);
        }
        
        public bool ReportError(string error) {
            TasksUnitTests.StackHashWebService.ReportErrorRequest inValue = new TasksUnitTests.StackHashWebService.ReportErrorRequest();
            inValue.Body = new TasksUnitTests.StackHashWebService.ReportErrorRequestBody();
            inValue.Body.error = error;
            TasksUnitTests.StackHashWebService.ReportErrorResponse retVal = ((TasksUnitTests.StackHashWebService.StackHashServiceSoap)(this)).ReportError(inValue);
            return retVal.Body.ReportErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TasksUnitTests.StackHashWebService.ReportErrorFromUserResponse TasksUnitTests.StackHashWebService.StackHashServiceSoap.ReportErrorFromUser(TasksUnitTests.StackHashWebService.ReportErrorFromUserRequest request) {
            return base.Channel.ReportErrorFromUser(request);
        }
        
        public bool ReportErrorFromUser(string error, string sender) {
            TasksUnitTests.StackHashWebService.ReportErrorFromUserRequest inValue = new TasksUnitTests.StackHashWebService.ReportErrorFromUserRequest();
            inValue.Body = new TasksUnitTests.StackHashWebService.ReportErrorFromUserRequestBody();
            inValue.Body.error = error;
            inValue.Body.sender = sender;
            TasksUnitTests.StackHashWebService.ReportErrorFromUserResponse retVal = ((TasksUnitTests.StackHashWebService.StackHashServiceSoap)(this)).ReportErrorFromUser(inValue);
            return retVal.Body.ReportErrorFromUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TasksUnitTests.StackHashWebService.CheckForUpdateResponse TasksUnitTests.StackHashWebService.StackHashServiceSoap.CheckForUpdate(TasksUnitTests.StackHashWebService.CheckForUpdateRequest request) {
            return base.Channel.CheckForUpdate(request);
        }
        
        public string CheckForUpdate(int clientMajor, int clientMinor, System.Guid clientInstance) {
            TasksUnitTests.StackHashWebService.CheckForUpdateRequest inValue = new TasksUnitTests.StackHashWebService.CheckForUpdateRequest();
            inValue.Body = new TasksUnitTests.StackHashWebService.CheckForUpdateRequestBody();
            inValue.Body.clientMajor = clientMajor;
            inValue.Body.clientMinor = clientMinor;
            inValue.Body.clientInstance = clientInstance;
            TasksUnitTests.StackHashWebService.CheckForUpdateResponse retVal = ((TasksUnitTests.StackHashWebService.StackHashServiceSoap)(this)).CheckForUpdate(inValue);
            return retVal.Body.CheckForUpdateResult;
        }
        
        public void ReportIndexStatistics(System.Guid serviceInstance, int contextId, int products, int files, int events, int eventInfos, int cabs, int maxEventCount) {
            base.Channel.ReportIndexStatistics(serviceInstance, contextId, products, files, events, eventInfos, cabs, maxEventCount);
        }
        
        public void ReportDotNetMiss(System.Guid serviceInstance, int contextId, int dotNetMajor, int dotNetMinor, int dotNetBuild, int dotNetPrivate) {
            base.Channel.ReportDotNetMiss(serviceInstance, contextId, dotNetMajor, dotNetMinor, dotNetBuild, dotNetPrivate);
        }
        
        public void RemoveTestData() {
            base.Channel.RemoveTestData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TasksUnitTests.StackHashWebService.GetLicenseResponse TasksUnitTests.StackHashWebService.StackHashServiceSoap.GetLicense(TasksUnitTests.StackHashWebService.GetLicenseRequest request) {
            return base.Channel.GetLicense(request);
        }
        
        public bool GetLicense(System.Guid licenseId, out string companyName, out string departmentName, out long maxEvents, out int maxSeats, out System.DateTime expiryUTC) {
            TasksUnitTests.StackHashWebService.GetLicenseRequest inValue = new TasksUnitTests.StackHashWebService.GetLicenseRequest();
            inValue.Body = new TasksUnitTests.StackHashWebService.GetLicenseRequestBody();
            inValue.Body.licenseId = licenseId;
            TasksUnitTests.StackHashWebService.GetLicenseResponse retVal = ((TasksUnitTests.StackHashWebService.StackHashServiceSoap)(this)).GetLicense(inValue);
            companyName = retVal.Body.companyName;
            departmentName = retVal.Body.departmentName;
            maxEvents = retVal.Body.maxEvents;
            maxSeats = retVal.Body.maxSeats;
            expiryUTC = retVal.Body.expiryUTC;
            return retVal.Body.GetLicenseResult;
        }
    }
}
