//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackHashDBConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StackHashDBConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel StackHash Database Configuration?.
        /// </summary>
        internal static string ConfirmCancel_MBMessage {
            get {
                return ResourceManager.GetString("ConfirmCancel_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel StackHash Database Configuration.
        /// </summary>
        internal static string ConfirmCancel_MBTitle {
            get {
                return ResourceManager.GetString("ConfirmCancel_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackHash failed to create the profile database..
        /// </summary>
        internal static string CreateFailed_MBMessage {
            get {
                return ResourceManager.GetString("CreateFailed_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create database - StackHash Database Configuration.
        /// </summary>
        internal static string CreateFailed_MBTitle {
            get {
                return ResourceManager.GetString("CreateFailed_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2005/2008.
        /// </summary>
        internal static string DatabaseTypeSqlServer {
            get {
                return ResourceManager.GetString("DatabaseTypeSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the following problems with the database configuration:
        ///{0}.
        /// </summary>
        internal static string Error_All {
            get {
                return ResourceManager.GetString("Error_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cab folder may not be a UNC path if database files are also stored in this folder. This is because SQL Server cannot guarantee database consistency when using a network share..
        /// </summary>
        internal static string Error_CabFolderIsUNC {
            get {
                return ResourceManager.GetString("Error_CabFolderIsUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cab folder does not exist. Please create the folder or select and existing, empty folder..
        /// </summary>
        internal static string Error_CabFolderMissing {
            get {
                return ResourceManager.GetString("Error_CabFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cab folder is already used by another profile. Please choose a different folder..
        /// </summary>
        internal static string Error_DuplicateCabFolder {
            get {
                return ResourceManager.GetString("Error_DuplicateCabFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name is already used by another profile. Please choose a different name..
        /// </summary>
        internal static string Error_DuplicateProfileName {
            get {
                return ResourceManager.GetString("Error_DuplicateProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name is invalid: {0}.
        /// </summary>
        internal static string Error_InvalidProfileName {
            get {
                return ResourceManager.GetString("Error_InvalidProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Invalid - StackHash Database Configuration.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cab folder is for a pre-Beta 7 profile. Please select a new folder for the upgrade. The current folder may be deleted once the profile upgrade has been completed..
        /// </summary>
        internal static string Error_UpgradeFolder {
            get {
                return ResourceManager.GetString("Error_UpgradeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download and install SQL Server 2008 R2 Express edition? This is the recommended database for StackHash. Click Yes to install automatically using recommended settings. Click No to choose a different database or to install SQL Server manually..
        /// </summary>
        internal static string InstallExpress_MBMessage {
            get {
                return ResourceManager.GetString("InstallExpress_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SQL Server 2008 R2 Express Edition?.
        /// </summary>
        internal static string InstallExpress_MBTitle {
            get {
                return ResourceManager.GetString("InstallExpress_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading SQL Server 2008 R2 Express Edition....
        /// </summary>
        internal static string InstallExpress_ProgressDownloading {
            get {
                return ResourceManager.GetString("InstallExpress_ProgressDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing SQL Server 2008 R2 Express Edition. Please wait, this will take a few minutes....
        /// </summary>
        internal static string InstallExpress_ProgressInstalling {
            get {
                return ResourceManager.GetString("InstallExpress_ProgressInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install SQL Server 2008 R2 Express Edition..
        /// </summary>
        internal static string InstallExpressFailed_MBMessage {
            get {
                return ResourceManager.GetString("InstallExpressFailed_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SQL Server 2008 R2 Express Edition.
        /// </summary>
        internal static string InstallExpressFailed_MBTitle {
            get {
                return ResourceManager.GetString("InstallExpressFailed_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install SQL Server 2008 R2 Express Edition (Error {0:X8})..
        /// </summary>
        internal static string InstallExpressFailedMBMessageWithCode {
            get {
                return ResourceManager.GetString("InstallExpressFailedMBMessageWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A STACKHASH instance of SQL Server has already been installed. Please select this from the list of available instances..
        /// </summary>
        internal static string InstanceInstalled_MBMessage {
            get {
                return ResourceManager.GetString("InstanceInstalled_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackHash Instance Installed.
        /// </summary>
        internal static string InstanceInstalled_MBTitle {
            get {
                return ResourceManager.GetString("InstanceInstalled_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to list available instances for the selected database type..
        /// </summary>
        internal static string InstanceListFailed_MBMessage {
            get {
                return ResourceManager.GetString("InstanceListFailed_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to list instances - StackHash Database Configuration.
        /// </summary>
        internal static string InstanceListFailed_MBTitle {
            get {
                return ResourceManager.GetString("InstanceListFailed_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reboot is required to complete the installation of SQL Server 2008 R2 Express Edition. Run StackHash again after rebooting to continue.
        ///
        ///Would you like to reboot now?.
        /// </summary>
        internal static string Reboot_MBMessage {
            get {
                return ResourceManager.GetString("Reboot_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Required - StackHash Database Configuration.
        /// </summary>
        internal static string Reboot_MBTitle {
            get {
                return ResourceManager.GetString("Reboot_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this Folder.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders|*..
        /// </summary>
        internal static string SelectFolderFilter {
            get {
                return ResourceManager.GetString("SelectFolderFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cab Folder - StackHash Database Configuration.
        /// </summary>
        internal static string SelectFolderTitle {
            get {
                return ResourceManager.GetString("SelectFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StackHash Service could not access the specified Cab Folder. Please check that the folder exists and that the account the StackHash Service is running under has permission to access it. 
        ///
        ///By default the StackHash Service runs as NETWORK SERVICE and cannot access a folder located in the profile for your user account..
        /// </summary>
        internal static string TestCabFolderFailed_MBMessage {
            get {
                return ResourceManager.GetString("TestCabFolderFailed_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access Cab Folder - StackHash Database Configuration.
        /// </summary>
        internal static string TestCabFolderFailed_MBTitle {
            get {
                return ResourceManager.GetString("TestCabFolderFailed_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StackHash Service failed to connect to the database: {0}.
        /// </summary>
        internal static string TestFailed_MBMessage {
            get {
                return ResourceManager.GetString("TestFailed_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to database - StackHash Database Configuration.
        /// </summary>
        internal static string TestFailed_MBTitle {
            get {
                return ResourceManager.GetString("TestFailed_MBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StackHash Service successfully connected to the selected database instance..
        /// </summary>
        internal static string TestSuccess_MBMessage {
            get {
                return ResourceManager.GetString("TestSuccess_MBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Succeeded - StackHash Database Configuration.
        /// </summary>
        internal static string TestSuccess_MBTitle {
            get {
                return ResourceManager.GetString("TestSuccess_MBTitle", resourceCulture);
            }
        }
    }
}
