//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackHash.WindowsErrorReporting.Services.Data.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataServicesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataServicesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StackHash.WindowsErrorReporting.Services.Data.API.DataServicesResources", typeof(DataServicesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failure reason.
        /// </summary>
        internal static string AUTHENTICATION_FAILURE_DATA_STRING {
            get {
                return ResourceManager.GetString("AUTHENTICATION_FAILURE_DATA_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and/or password are incorrect..
        /// </summary>
        internal static string BAD_USERNAME_PASSWORD {
            get {
                return ResourceManager.GetString("BAD_USERNAME_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company account has been disabled..
        /// </summary>
        internal static string COMPANY_DISABLED {
            get {
                return ResourceManager.GetString("COMPANY_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred. Please contact the WER support team [e-mail: wer@microsoft.com] for assistance..
        /// </summary>
        internal static string FEED_EXCEPTION_DEFAULT_MESSAGE {
            get {
                return ResourceManager.GetString("FEED_EXCEPTION_DEFAULT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access violation. You are not allowed to access the resource you requested..
        /// </summary>
        internal static string GENERAL_ACCESS_EXCEPTION {
            get {
                return ResourceManager.GetString("GENERAL_ACCESS_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while trying to authenticate the username and password. Please check the FeedAuthenticationException class object&apos;s Data collection for possible failure reasons. Browse to the Microsoft Winqual website at https://winqual.microsoft.com and try to login using the same username and password. The website will give you additional information about the error..
        /// </summary>
        internal static string GENERAL_AUTHENTICATION_EXCEPTION {
            get {
                return ResourceManager.GetString("GENERAL_AUTHENTICATION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password may have expired..
        /// </summary>
        internal static string PASSWORD_EXPIRED {
            get {
                return ResourceManager.GetString("PASSWORD_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been locked..
        /// </summary>
        internal static string PASSWORD_LOCKED {
            get {
                return ResourceManager.GetString("PASSWORD_LOCKED", resourceCulture);
            }
        }
    }
}
